name: Deploy to staging
on: 
  push:
    branches:
      - "main"

jobs:
  redeploy_everything:
    name: Deploying the everything to staging cluster
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        run: |
          # 1. Setup the SSH key file and set correct permissions
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key
          
          # 2. Execute the commands INSIDE the remote AWS server
          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@13.206.197.40 << 'EOF'
            cd devops-project
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server
          EOF
